- docs/AboutUs.md
> Update AboutUs Page with Juraimi's Details

- docs/DeveloperGuide.md
> Update Developer Guide with product scope details

- docs/DeveloperGuide.md
> Update Developer Guide with MVP User Stories

- docs/DeveloperGuide.md
> docs: add an NFR, use case, and glossary terms

- docs/DeveloperGuide.md
> Add remaining user stories to DG

- docs/DeveloperGuide.md
> Add Use Case, NFR to DG

- docs/DeveloperGuide.md
Add use case for viewing all contacts and 1 NFR
#37 #38
> Add use case and NFR

- src/main/java/seedu/address/commons/util/StringUtil.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
> Add basic search functionality

- src/main/resources/view/PersonListCard.fxml
> Add new fields

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
> Fix Find Command Behaviour

- docs/UserGuide.md
> Update UG for the Find Command

- docs/UserGuide.md
> docs Update UserGuide to show new Add Command syntax

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/main/java/seedu/address/model/person/PersonTagsContainsSearchPredicate.java
> feat: add filter command functionality (filter contacts on tags)

- docs/UserGuide.md
> docs edit user guide to indicate special "hiring" tag

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
> Enhance Find command functionality

- src/main/java/seedu/address/logic/commands/SortCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Name.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
> Add basic sort functionality

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Importance.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalAddressBook.java
> Add field to person class

- docs/UserGuide.md
> Update UG with new Add/Edit Command Enhancements

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
> Fix Find functionality

- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Importance.java
> Fix Accepted Values for Importance Class

- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/logic/parser/SortComparator.java
> Enhance Sort Command with new Importance Field

- src/main/java/seedu/address/logic/commands/ListMeetingsCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/MeetingCard.java
- src/main/java/seedu/address/ui/MeetingListPanel.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/MeetingListCard.fxml
- src/main/resources/view/MeetingListPanel.fxml
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
> Create list meetings feature

- docs/diagrams/ModelClassDiagram.puml
Remove Address and add in Company and Position
Resolves #113
> docs: edit ModelClassDiagram

- src/main/java/seedu/address/ui/HelpWindow.java
> fix(UI): resolve scanner nextline issues

- build.gradle
> Enable Support of Java Assertions

- docs/DeveloperGuide.md
- docs/UserGuide.md
Added new use cases for meeting functionality. 
Fixes #127
> Updated DeveloperGuide.md

- build.gradle
- src/main/java/seedu/address/logic/parser/SortCommandParser.java
- src/main/java/seedu/address/ui/HelpWindow.java
> Fix help command not displaying UG

- docs/UserGuide.md
> Add syntax changes and line breaks for readability

- docs/UserGuide.md
- src/main/java/seedu/address/model/meeting/MeetingTime.java
> Add date time validation

- docs/UserGuide.md
> Update UG for edit meetings

- src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
> Fix formatting of error message when adding meeting

- src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
- src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
> Disallow empty contact when editing meeting

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
> Prevent deletion of contact if contact has existing meetings

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
> Update meeting list with new name when editing contact name

- src/main/java/seedu/address/logic/Messages.java
> Add commas between names for message when meeting is successfully created

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/_sass/minima/_base.scss
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
- src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
- src/main/java/seedu/address/ui/MeetingCard.java
- src/main/resources/view/MainWindow.fxml
Fixes:
#231 #230 #229 #222 #217 #212 #211 #204 #201 #196 #191 #187 #186 #179 #177 #176 #175 #174
> Documentation bugs

- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/meeting/MeetingTime.java
> Fix datetime parser issue for invalid dates

- docs/UserGuide.md
- src/main/java/seedu/address/model/person/Importance.java
> Fix importance display error

- src/main/java/seedu/address/logic/commands/SortCommand.java
> Fix error message that stated wrong sort parameters

- docs/DeveloperGuide.md
- docs/UserGuide.md
Resolves #227 
Resolves #203 
Resolves #190
> Update UG and DG with fixed command implementations

- docs/DeveloperGuide.md
> Add acknowledgements
